// Generated by CoffeeScript 1.7.1
(function() {
  var app, bw, ipc, tray, win;

  app = require('app');

  bw = require('browser-window');

  tray = require('tray');

  ipc = require('ipc');

  win = null;

  app.on('ready', function() {
    var options, trayObj;
    options = {
      width: 500,
      height: 200,
      frame: false
    };
    win = new bw(options);
    win.loadUrl('file://' + __dirname + '/test.html');
    trayObj = new tray(__dirname + '/tray.png');
    return trayObj.on('clicked', function(event, bounds) {
      return win.show();
    });
  });

  ipc.on('min', function(e, age) {
    return win.hide();
  });

}).call(this);
